name: SSH via Ngrok (Token Configurado)
on:
  push:
    branches:
      - main

jobs:
  ssh-ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar usuário SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo useradd -m -s /bin/bash devuser
          echo "devuser:password123" | sudo chpasswd
          echo "devuser ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/devuser > /dev/null

      - name: Iniciar serviço SSH
        run: sudo service ssh start

      - name: Instalar ngrok e configurar token
        run: |
          # Baixar e instalar o ngrok
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz 
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin/

          # Configurar token no arquivo de configuração do ngrok
          ngrok config add-authtoken 1vgZrCA9yJDURy3OK1gNbS2G610_3CX2e2bqT4Ee88uMBk5he

      - name: Iniciar túnel TCP com ngrok
        run: |
          # Iniciar ngrok em segundo plano
          ngrok tcp 22 &

          # Aguardar o túnel ser criado
          sleep 10

          # Obter endereço exposto
          PUBLIC_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "🔗 Conecte-se via SSH: ssh devuser@${PUBLIC_URL#*@} -p ${PUBLIC_URL##*:}"

      - name: Manter o contêiner em execução
        run: sleep 1000000
